// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActiveCharacter() {
  return window['go']['main']['App']['GetActiveCharacter']();
}

export function GetCharacters() {
  return window['go']['main']['App']['GetCharacters']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetCharacter(arg1) {
  return window['go']['main']['App']['SetCharacter'](arg1);
}

export function SetVAD(arg1) {
  return window['go']['main']['App']['SetVAD'](arg1);
}

export function StartPTT() {
  return window['go']['main']['App']['StartPTT']();
}

export function StopPTT() {
  return window['go']['main']['App']['StopPTT']();
}
