// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetActiveCharacter():Promise<string>;

export function GetCharacters():Promise<Array<main.CharacterInfo>>;

export function SendMessage(arg1:string):Promise<void>;

export function SetCharacter(arg1:string):Promise<void>;

export function SetVAD(arg1:boolean):Promise<void>;

export function StartPTT():Promise<void>;

export function StopPTT():Promise<void>;
